### PR TITLE
Beta 2

### PR DESCRIPTION
**Pull request by etiennegingras**
Remove @villedemontreal/lint-config :-)
Remove tslint and prettier scripts
Replace by lint with eslin/prettier
Use prettier config defaults

### CODE REVIEW

**Comment by electrotype** [comment]
- The scripts used by the library _itself_ should be located in `/scripts` and not in `src/scripts`. If you look at https://github.com/etiennegingras/node-scripting/blob/beta-2/run you will see that the variable `scriptsIndexModule` points to `./scripts/index`. It is in this Index file that you should export the scripts used _by the library itself_. Once the scripts have been moved from `src/scripts` to `/scripts`, we will have to adjust this Index `/scripts/index.ts` so that it exports these scripts... Then running `./run lint` into the library itself should work.

- The file https://github.com/etiennegingras/node-scripting/blob/beta-2/src/coreScriptBase.ts should be deleted because there is no more notion of "core" scripts provided by the library. Projects/libraries will now have to define their own scripts, including `lint` and `lint-fix`. It is in the API and library _templates_ that we will put these default scripts.

- We need to rework the `/src/main.ts` file so that no more core scripts are added automatically.

You can refer to my PR on Bitbucket for more details on these points.

Once these points have been worked on, I will revisit your PR. Thank you!

**Comment by electrotype** [comment]
Also, the library should have a major version increase (ie: `2.0.0`) because there are breaking changes.

**Comment by livetocode** [comment]
Could you adjust the prettier config in order to use single quotes, to avoid all this noise in the diff, especially since it we are using all over the place in our code base!
See singleQuote option in https://prettier.io/docs/en/configuration.html
Tks.

**Comment by psionikangel** [comment]
@etiennegingras Est-ce que cette version est prête à être révisée?

**Review by livetocode — APPROVED** [review]

**Pull request merged**
